//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaCrud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public short idVideo { get; set; }
        public string nombre { get; set; }
        public byte idFormato { get; set; }
    
        public virtual Formato Formato { get; set; }
    }
}
