//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multiservicios_WebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaTarjeta
    {
        public int idVenta { get; set; }
        public short idCliente { get; set; }
        public byte idTarjeta { get; set; }
        public string codigo { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
